const mongoose = require("mongoose");
const Auspice = require("./auspice");
const Power = require("./power");
const Attributes = require("./attributes");

const { Schema } = mongoose;

const Character = new Schema({
  code: {
    required: true,
    type: Number,
  },
  player: {
    required: true,
    type: String,
    unique: false,
  },
  character: {
    required: true,
    type: String,
    unique: false,
  },
  email: {
    type: String,
    unique: false,
    required: false,
  },
  tribe: {
    required: true,
    type: String,
    unique: false,
  },
  clan: {
    required: true,
    type: String,
    unique: false,
  },
  pack: {
    required: true,
    type: String,
    unique: false,
  },
  alliance: {
    required: true,
    type: String,
    unique: false,
  },
  nature: {
    required: true,
    type: String,
    unique: false,
  },
  attitude: {
    required: true,
    type: String,
    unique: false,
  },
  gnose: {
    required: true,
    type: Number,
    unique: false,
  },
  willpower: {
    required: true,
    type: Number,
    unique: false,
  },
  auspice: {
    type: Auspice,
    required: true,
    default: {},
  },
  auspicePower: {
    type: [Power, Power, Power, Power],
    required: false,
    default: [],
  },
  attributes: {
    type: Attributes,
    required: true,
    default: {
      str: 1,
      dex: 1,
      sta: 1,
      app: 1,
      man: 1,
      cha: 1,
      per: 1,
      int: 1,
      wit: 1,
    },
  },
  avantages: {
    type: [Power, Power, Power, Power, Power, Power, Power, Power],
    default: [],
  },
  talents: {
    type: [
      Power,
      Power,
      Power,
      Power,
      Power,
      Power,
      Power,
      Power,
      Power,
      Power,
      Power,
      Power,
      Power,
      Power,
    ],
    default: [],
  },
  skills: {
    type: [
      Power,
      Power,
      Power,
      Power,
      Power,
      Power,
      Power,
      Power,
      Power,
      Power,
      Power,
      Power,
      Power,
      Power,
      Power,
      Power,
      Power,
      Power,
      Power,
      Power,
      Power,
      Power,
      Power,
      Power,
      Power,
      Power,
      Power,
      Power,
      Power,
      Power,
      Power,
      Power,
      Power,
      Power,
    ],
    default: [],
  },
  language: {
    type: [Power, Power, Power, Power, Power],
    default: [],
  },
  legends: {
    type: [
      Power,
      Power,
      Power,
      Power,
      Power,
      Power,
      Power,
      Power,
      Power,
      Power,
      Power,
      Power,
      Power,
      Power,
      Power,
      Power,
      Power,
      Power,
      Power,
      Power,
      Power,
      Power,
      Power,
      Power,
      Power,
      Power,
    ],
    default: [],
  },
  politics: {
    type: [
      Power,
      Power,
      Power,
      Power,
      Power,
      Power,
      Power,
      Power,
      Power,
      Power,
      Power,
      Power,
      Power,
      Power,
      Power,
      Power,
      Power,
      Power,
      Power,
      Power,
      Power,
      Power,
      Power,
      Power,
      Power,
      Power,
    ],
    default: [],
  },
  wod: {
    type: [
      Power,
      Power,
      Power,
      Power,
      Power,
      Power,
      Power,
      Power,
      Power,
      Power,
      Power,
      Power,
    ],
    default: [],
  },
  dons: {
    type: [Power, Power],
    default: [],
  },
  rituals: {
    type: [Power, Power, Power, Power, Power, Power, Power, Power],
    default: [],
  },
  cry: {
    type: [Power, Power, Power, Power, Power, Power],
    default: [],
  },
  bonusAuspice: {
    type: Power,
    default: {},
  },
});

module.exports = Character;
